tachiyomi.domain.manga.model.Manga
tachiyomi.domain.chapter.model.Chapter
tachiyomi.domain.library.model.LibraryManga
tachiyomi.domain.category.model.Category
eu.kanade.tachiyomi.ui.library.LibraryItem
